package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("AT web_shop")
    void generatedTest() {
        step("Open 'http://demowebshop.tricentis.com/login'", () -> {
            step("// todo: just add selenium action");
        });

        step("Set Email 'test_web_shop@mail.ru'", () -> {
            step("// todo: just add selenium action");
        });

        step("Set Password 'Selenium123'", () -> {
            step("// todo: just add selenium action");
        });

        step("Verify succesfull authorization as 'test_web_shop@mail.ru'", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'http://demowebshop.tricentis.com/login'", () ->
            open("http://demowebshop.tricentis.com/login"));

        step("Page title should have text 'Demo Web Shop. Login'", () -> {
            String expectedTitle = "Demo Web Shop. Login";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'http://demowebshop.tricentis.com/login'", () ->
            open("http://demowebshop.tricentis.com/login"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}